In [62]:
# This Notebooks is a basic tutorial for Numpy Arrays
import numpy as np
import matplotlib.pyplot as plt

In [79]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [63]:
# What is an array per definition?
# What is a matrix
# What is a tensor
arr = np.array([1,2,3,7,8,9])
arr_2 = np.array([1,2,1,2,1,2])
arr_3 = np.array(["hell",1,2,3])

In [64]:
# other form of creation
# arrange(start, stop, interval)
array = np.arange(10)

array([1, 3])

In [66]:
# operators on arrays
# Vectorization is key
print(array + 10)
print(array - 1)
print(array/1)
print(array%3)
print(array**2)
# these are just wrappers around
#np.add()
#np.substract()
#np.divide()
#...

[10 11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7  8]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 0 1 2 0 1 2 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [70]:
array_1 = np.arange(-4,5,1)
np.abs(array_1)

array([4, 3, 2, 1, 0, 1, 2, 3, 4])

In [71]:
# for more advanced stuff it might be necessary to directly give the output of a 
# numpy function 


y = 5
z = np.empty(9) # third array 
np.multiply(array_1,y, out = z) # put computation inside the empty array
print(z)

[-20. -15. -10.  -5.   0.   5.  10.  15.  20.]


In [74]:
# create a random numpy array that we can work with
# go through the dimensions and ask what might be a data structure that uses this shape
print(np.random.rand(10))
print(np.random.rand(10,2))

[0.63497467 0.17550756 0.257194   0.94926463 0.26155921 0.83966975
 0.93077629 0.05321069 0.80966817 0.27420607]
[[0.14725658 0.27099263]
 [0.89704518 0.92040092]
 [0.8291483  0.93484447]
 [0.46667441 0.62533698]
 [0.71626303 0.65102979]
 [0.06600402 0.53276599]
 [0.02187036 0.83059754]
 [0.66704829 0.51287704]
 [0.84071019 0.54976005]
 [0.37081244 0.07702974]]


In [75]:
# Create a linear spaced array
print(np.linspace(1,100, 10))

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [78]:
# slice the array
# [row, columns]
print(array[:5])
# try with an array of 3 dimensions, how would slicing work what kind of data would this represent
# task: Get the first 50 elements from both columns/the whole array
# get every element placed on an even index from the first column

[0 1 2 3 4]


In [34]:
# create a vector of an specific length in advance already prefilled
# this might be important 
zeros = np.zeros((2,3))
ones = np.ones((2,3))
identity = np.identity(3) # is a squared matrix that can be used to calculate serveral matrix specific things

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
# we can also create a vector from a normal distribtuion
# (mean, std, samples)
# ofc mean and std can vary slidely
arr_normal = np.random.normal(5, 5,20)

In [83]:
# we can calculate descriptive statistics using plain numpy
print(f"The mean value of the array: {arr_normal.mean()}")
print(f"The standard deviation of the array: {arr_normal.std()}")
print(f"The sum of the array:  {arr_normal.sum()}")
print(f"The shape of the array: {arr_normal.shape}")
print(f"The maximum value of the array: {arr_normal.max()}")
print(f"The minimum value of the array: {arr_normal.min()}")
print(f"Highest value located at: {arr_normal.argmax()} ")
print(f"Lowest value located at: {arr_normal.argmin()}")
print(f"Sorted array indeces looks like this: {arr_normal.argsort()}")
print(f"Sorted array looks like this: {np.sort(arr_normal)}")
-np.sort(-arr_normal) # what would this be? and why is this working?

The mean value of the array: 4.978774695567958
The standard deviation of the array: 4.632643244413415
The sum of the array:  99.57549391135916
The shape of the array: (20,)
The maximum value of the array: 11.885478465002244
The minimum value of the array: -5.145511547990791
Highest value located at: 1 
Lowest value located at: 4
Sorted array indeces looks like this: [ 4  5  8 16 13 18 19 15  0 10  7  3  2  6 11  9 12 14 17  1]
Sorted array looks like this: [-5.14551155 -2.38645638 -1.49957612 -1.31910661  1.12509332  3.74964936
  4.14325923  4.47618349  4.54464507  5.46276233  5.8072671   6.13763436
  7.20939312  7.39490073  7.95323199  8.85059133  9.74396558 10.52796737
 10.91412172 11.88547847]


array([11.88547847, 10.91412172, 10.52796737,  9.74396558,  8.85059133,
        7.95323199,  7.39490073,  7.20939312,  6.13763436,  5.8072671 ,
        5.46276233,  4.54464507,  4.47618349,  4.14325923,  3.74964936,
        1.12509332, -1.31910661, -1.49957612, -2.38645638, -5.14551155])

In [42]:
# Exercise for students:
# get the mean heights of all the presidents
# get the std 
# calculate the percentile for the lower quarter and the higher quarter
# calculate the median
# get the index of the highest value
import pandas as pd
heights = pd.read_csv("../Data/ExampleData/president_heights.csv")
only_heights = heights['height(cm)'].values

In [43]:
np.percentile(only_heights, 25)
np.percentile(only_heights, 75)

Index(['order', 'name', 'height(cm)'], dtype='object')


183.0

In [27]:
# per definition a vector transpose represent the switch from row to column or vice versa
vector_transpose = np.array([1,2,3,4])
matrix_transpose = np.array([[1,2,3,4], [1,2,3,4]])
matrix_transpose

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [28]:
# matrix and vector transpositions
# matrix is switching from columns to row or vice versa
# vector appears to not change
print(matrix_transpose.transpose())
print(vector_transpose.transpose())

array([1, 2, 3, 4])

In [35]:
# We can also reshape our arrays into multiple new shapes
arr_1 = np.array([[1,2],[3,2], [1,4]])
print(f"This is the original array: {arr_1}")
flatten_array = np.reshape(arr_1, -1)
print(f"This is the flatten array: {flatten_array}")
reshape = np.reshape(arr_1, (2,3))
print(f"This is the reshaped array: {reshape}")

This is the original array: [[1 2]
 [3 2]
 [1 4]]
This is the flatten array: [1 2 3 2 1 4]
This is the reshaped array: [[1 2 3]
 [2 1 4]]


In [37]:
# Broadcasting
# Describes the combination of two vector, matrices of different sizes
array_2 = np.linspace(1,10,10) + np.linspace(5,14,10)
# how would you think is this operation going?
array_2

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [40]:
# But Broadcasting describes the operation using unequal sizes
# e.g using a scaler
print(array_2 * 5)
print(array_2 + 10)
print(array_2 * 10)


[ 30.  40.  50.  60.  70.  80.  90. 100. 110. 120.]
[16. 18. 20. 22. 24. 26. 28. 30. 32. 34.]
[ 60.  80. 100. 120. 140. 160. 180. 200. 220. 240.]


In [50]:
# why is this in general important
# it is all about vectorization
arr_1 = np.array([[1,2,3],[3,2,1]])
multiply_arr = np.array([1,2,3])
scal_arr = arr_1 * 5
vec_arr = arr_1 + multiply_arr
print(scal_arr) # what happens here 
print(vec_arr) # what happens here

[[ 5 10 15]
 [15 10  5]]
[[2 4 6]
 [4 4 4]]


In [57]:
# this calculates the dot product
# this dot product is usually a metric that shows how aligned to entities are
# if dot product is zero than vectors are orthogonal
dot_vector = np.arange(3)
dot_vector_2 = np.arange(3)
calculated_vector = dot_vector.dot(dot_vector_2)
calculated_matrix = arr_1.dot(dot_vector)
print(calculated_vector)
print(calculated_matrix)

5
[8 4]


In [58]:
# this is matrix multiplication 
# usually you use matmul for matrix multiplication things and dot product for vectors
arr_1 @ dot_vector

array([8, 4])

In [59]:
# let us retrieve the point by point differences
diff_array = np.linspace(1,100, 10)
diff_1 = np.diff(diff_array)
diff_1

array([11., 11., 11., 11., 11., 11., 11., 11., 11.])

In [60]:
# and one last function:
# 2d convolution is useful to apply 
array = np.array([1,3,5,7,9,11,15,20,40,80])
moving_average = np.convolve(array, np.array([0.33,0.33, 0.33])) # second represents the length
moving_average
# Can you imaging another application where this is widely used

array([ 0.33,  1.32,  2.97,  4.95,  6.93,  8.91, 11.55, 15.18, 24.75,
       46.2 , 39.6 , 26.4 ])

In [44]:
# exercies calculate the mean, std, maximum and the sum of the array
# reshape the array into a 3x2 matrix
# then add the vector [2,2,2] to it and reshape back to one dimension array
# recalculate the mean, std, maximum and the sum
first_array = np.array([1.5,1.2,3.1,3.6,9,15])

In [61]:
# numpy vectorize
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b
    
my_function = np.vectorize(myfunc)
my_function([1,2,3,4,5,5,7],2)

array([3, 4, 1, 2, 3, 3, 5])